name: authentication_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.4.9
  formz: ^0.6.1
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - google_fonts/montserrat_alternates/
